### ISSUE TITLE
External ID not found in the system: sythil_saas_client.saas_user

### ISSUE THREAD

**Issue by EshanMaini** [SythilTech/Odoo9#20]
Hii i am having this error when i try to create a user from signup form.

error traceback
------------------------------------------------------
Traceback (most recent call last):
  File "/odoo/odoo-server/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 158, in _handle_exception
    return request._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 786, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 183, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/openerp/http.py", line 845, in dispatch
    r = self._call_function(**self.params)
  File "/odoo/odoo-server/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/sythil_saas_server/controllers/main.py", line 129, in template_details
    saas_user_id = registry['ir.model.data'].get_object_reference(cr, SUPERUSER_ID, 'sythil_saas_client', 'saas_user')[1]
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1033, in get_object_reference
    return self.xmlid_lookup(cr, uid, "%s.%s" % (module, xml_id))[1:3]
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "<decorator-gen-3>", line 2, in xmlid_lookup
  File "/odoo/odoo-server/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 991, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ValueError: External ID not found in the system: sythil_saas_client.saas_user

---------------------------------------------------------------------------

**Comment by SythilTech** [comment]
Hello,

You need to install the sythil_saas_client module in your template database for it to work.

Regards
Steven
